name: Deploy para AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configurar AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1b

      - name: Enviar aplicação para EC2
        run: |
          scp -i "seu_arquivo.pem" -r * ec2-user@52.1.184.118:
          ssh -i "seu_arquivo.pem" ec2-user@52.1.184.118 "nohup ./mvnw spring-boot:run
